"""Repository and unit-of-work ports.

The unit of work makes plan activation atomic: a new immutable version is saved
and ``active_version_id`` is flipped together, or neither happens. Idempotency
is keyed on the provider event id so duplicate inbound events do not double-write.
"""

from __future__ import annotations

from types import TracebackType
from typing import Protocol

from ..domain.audit import AuditEvent
from ..domain.checkin import DailyCheckIn, Observation
from ..domain.identity import CaregiverAccount, DependentProfile
from ..domain.ids import (
    CaregiverId,
    DependentId,
    PlanId,
    ProposalRef,
    ProviderEventId,
)
from ..domain.media import MediaDocument
from ..domain.plan import MedicalPlan, PlanProposal
from ..domain.safety_decision import SafetyDecision
from ..domain.treatment import TreatmentMention
from ..domain.views import CaregiverExport, DependentTimeline, DeletionReceipt


class Repository(Protocol):
    # identity
    def add_caregiver(self, account: CaregiverAccount) -> None: ...
    def get_caregiver(self, caregiver_id: CaregiverId) -> CaregiverAccount | None: ...
    def find_caregiver_by_identity(
        self, channel: str, opaque_id: str
    ) -> CaregiverAccount | None: ...
    def add_dependent(self, profile: DependentProfile) -> None: ...
    def get_dependent(self, dependent_id: DependentId) -> DependentProfile | None: ...

    # plans
    def add_plan(self, plan: MedicalPlan) -> None: ...
    def save_plan(self, plan: MedicalPlan) -> None: ...
    def get_plan(self, plan_id: PlanId) -> MedicalPlan | None: ...
    def get_plan_for_dependent(self, dependent_id: DependentId) -> MedicalPlan | None: ...

    # proposals
    def add_proposal(self, ref: ProposalRef, proposal: PlanProposal) -> None: ...
    def get_proposal(self, ref: ProposalRef) -> PlanProposal | None: ...
    def mark_proposal_rejected(self, ref: ProposalRef) -> None: ...

    # facts / timeline
    def add_treatment_mention(self, mention: TreatmentMention) -> None: ...
    def add_checkin(self, checkin: DailyCheckIn) -> None: ...
    def add_observation(self, observation: Observation) -> None: ...
    def add_media(self, media: MediaDocument) -> None: ...
    def add_safety_decision(self, decision: SafetyDecision) -> None: ...
    def timeline_for_dependent(self, dependent_id: DependentId) -> DependentTimeline: ...

    # idempotency
    def result_for_provider_event(
        self, provider_event_id: ProviderEventId
    ) -> str | None: ...
    def remember_provider_event(
        self, provider_event_id: ProviderEventId, result_ref: str
    ) -> None: ...

    # audit
    def add_audit(self, event: AuditEvent) -> None: ...
    def audit_for_caregiver(self, caregiver_id: CaregiverId) -> tuple[AuditEvent, ...]: ...

    # export / deletion
    def export_caregiver(self, caregiver_id: CaregiverId) -> CaregiverExport: ...
    def delete_caregiver(self, caregiver_id: CaregiverId) -> DeletionReceipt: ...


class UnitOfWork(Protocol):
    repo: Repository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
